#include <stdio.h>
#include "html-generator.h"
#include <sys/stat.h>
#include <string.h>
#include <stdlib.h>

void insert_html_tag_and_exit(char *tag, char *attributes);
void insert_html_tag_with_text(char *tag, char *attributes, char *text);
void add_css();
void insert_boilerplate();
void insert_navbar();
void insert_main_page();
void insert_recipe_card(const char *title, int rating/*, const char *image_address*/);

int main() {
    add_css();
    generate_html_file("styles.css");
    delete_html_code();

    insert_main_page();
    generate_html_file("index.html");
    delete_html_code();

    return 0;

    insert_html_text(
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            "    <link\n"
            "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link\n"
            "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link href=\"styles.css\" rel=\"stylesheet\" />\n"
            "    <title>Reginos Receptai | Apie mus</title>\n"
            "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
            "    <link\n"
            "      rel=\"stylesheet\"\n"
            "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
            "    />\n"
            "  </head>\n"
            "  <body class=\"pb-4\">\n"
            "    <!-- Navbar -->\n"
            "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
            "      <div class=\"container-md px-3\">\n"
            "        <a class=\"navbar-brand\" href=\"./index.html\">Reginos Receptai</a>\n"
            "        <button\n"
            "          class=\"navbar-toggler\"\n"
            "          type=\"button\"\n"
            "          data-bs-toggle=\"collapse\"\n"
            "          data-bs-target=\"#navbarSupportedContent\"\n");
    insert_html_text( "          aria-controls=\"navbarSupportedContent\"\n"
            "          aria-expanded=\"false\"\n"
            "          aria-label=\"Toggle navigation\"\n"
            "        >\n"
            "          <span class=\"navbar-toggler-icon\"></span>\n"
            "        </button>\n"
            "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
            "          <ul class=\"navbar-nav ms-auto\">\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"./index.html\">Receptai</a>\n"
            "            </li>\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"./apie.html\">Apie mus</a>\n"
            "            </li>\n"
            "          </ul>\n"
            "        </div>\n"
            "      </div>\n"
            "    </nav>\n"
            "\n"
            "    <!-- Page content -->\n"
            "    <div class=\"container-md px-3\">\n"
            "      <div\n"
            "        class=\"page-header d-flex flex-wrap mb-2 justify-content-between align-items-center\"\n"
            "      >\n"
            "        <h2 class=\"h5 mb-0 py-2\">Apie mus</h2>\n"
            "      </div>\n"
            "      <p>Mes nesame atsakingi už tai, kaip jausitės po valgio.</p>\n"
            "    </div>\n"
            "  </body>\n"
            "</html>"
            );

    generate_html_file("apie.html");
    delete_html_code();

    mkdir("receptai");
    insert_html_text(
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            "    <link\n"
            "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link\n"
            "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
            "    <title>Ryžiadešriai | Reginos Receptai</title>\n"
            "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
            "    <link\n"
            "      rel=\"stylesheet\"\n"
            "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
            "    />\n"
            "  </head>\n"
            "  <body class=\"pb-4\">\n"
            "    <!-- Navbar -->\n"
            "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
            "      <div class=\"container-md px-3\">\n"
            "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
            "        <button\n"
            "          class=\"navbar-toggler\"\n"
            "          type=\"button\"\n"
            "          data-bs-toggle=\"collapse\"\n"
            "          data-bs-target=\"#navbarSupportedContent\"\n"
            "          aria-controls=\"navbarSupportedContent\"\n"
            "          aria-expanded=\"false\"\n"
            "          aria-label=\"Toggle navigation\"\n"
            "        >\n"
            "          <span class=\"navbar-toggler-icon\"></span>\n"
            "        </button>\n"
            "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
            "          <ul class=\"navbar-nav ms-auto\">\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
            "            </li>\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
            "            </li>\n"
            "          </ul>\n"
            "        </div>\n"
            "      </div>\n"
            "    </nav>\n"
            "\n"
            "    <!-- Page content -->\n"
            "    <div class=\"container-md px-3\">\n"
            "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
            "        <h2 class=\"h2 mb-0 py-1\">Ryžiadešriai</h2>\n"
            "        <div>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star\"></span>\n"
            "        </div>\n"
            "      </div>\n"
            "      <img\n"
            "        src=\"../assets/recipe_1_img.jpg\"\n"
            "        class=\"img-fluid recipe-img mb-3\"\n"
            "        alt=\"\"\n"
            "      />\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
            "      <ul class=\"list-group\">\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">1 pakelis dešrelių </span>\n"
            "        </li>\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">200 g ryžių</span>\n"
            "        </li>\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">3 pomidorų padažo</span>\n"
            "        </li>\n"
            "      </ul>\n"
            "    </div>\n"
            "  </body>\n"
            "</html>"
            );

    generate_html_file("receptai/1.html");
    delete_html_code();

    insert_html_text(
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            "    <link\n"
            "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link\n"
            "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
            "    <title>Pieniška agurkų sriuba | Reginos Receptai</title>\n"
            "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
            "    <link\n"
            "      rel=\"stylesheet\"\n"
            "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
            "    />\n"
            "  </head>\n"
            "  <body class=\"pb-4\">\n"
            "    <!-- Navbar -->\n"
            "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
            "      <div class=\"container-md px-3\">\n"
            "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
            "        <button\n"
            "          class=\"navbar-toggler\"\n"
            "          type=\"button\"\n"
            "          data-bs-toggle=\"collapse\"\n"
            "          data-bs-target=\"#navbarSupportedContent\"\n"
            "          aria-controls=\"navbarSupportedContent\"\n"
            "          aria-expanded=\"false\"\n"
            "          aria-label=\"Toggle navigation\"\n"
            "        >\n"
            "          <span class=\"navbar-toggler-icon\"></span>\n"
            "        </button>\n"
            "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
            "          <ul class=\"navbar-nav ms-auto\">\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
            "            </li>\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
            "            </li>\n"
            "          </ul>\n"
            "        </div>\n"
            "      </div>\n"
            "    </nav>\n"
            "\n"
            "    <!-- Page content -->\n"
            "    <div class=\"container-md px-3\">\n"
            "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
            "        <h2 class=\"h2 mb-0 py-1\">Pieniška agurkų sriuba</h2>\n"
            "        <div>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star\"></span>\n"
            "          <span class=\"fa fa-star\"></span>\n"
            "        </div>\n"
            "      </div>\n"
            "      <img\n"
            "        src=\"../assets/recipe_2_img.jpg\"\n"
            "        class=\"img-fluid recipe-img mb-3\"\n"
            "        alt=\"\"\n"
            "      />\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
            "      <ul class=\"list-group\">\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">200 ml šilto pieno</span>\n"
            "        </li>\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">3 dideli agurkai</span>\n"
            "        </li>\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">2 šaukštai skysto medaus</span>\n"
            "        </li>\n"
            "      </ul>\n"
            "    </div>\n"
            "  </body>\n"
            "</html>"
    );

    generate_html_file("receptai/2.html");
    delete_html_code();

    insert_html_text(
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            "    <link\n"
            "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link\n"
            "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
            "      rel=\"stylesheet\"\n"
            "    />\n"
            "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
            "    <title>Česnako skiltelės su klevų sirupu | Reginos Receptai</title>\n"
            "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
            "    <link\n"
            "      rel=\"stylesheet\"\n"
            "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
            "    />\n"
            "  </head>\n"
            "  <body class=\"pb-4\">\n"
            "    <!-- Navbar -->\n"
            "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
            "      <div class=\"container-md px-3\">\n"
            "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
            "        <button\n"
            "          class=\"navbar-toggler\"\n"
            "          type=\"button\"\n"
            "          data-bs-toggle=\"collapse\"\n"
            "          data-bs-target=\"#navbarSupportedContent\"\n"
            "          aria-controls=\"navbarSupportedContent\"\n"
            "          aria-expanded=\"false\"\n"
            "          aria-label=\"Toggle navigation\"\n"
            "        >\n"
            "          <span class=\"navbar-toggler-icon\"></span>\n"
            "        </button>\n"
            "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
            "          <ul class=\"navbar-nav ms-auto\">\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
            "            </li>\n"
            "            <li class=\"nav-item\">\n"
            "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
            "            </li>\n"
            "          </ul>\n"
            "        </div>\n"
            "      </div>\n"
            "    </nav>\n"
            "\n"
            "    <!-- Page content -->\n"
            "    <div class=\"container-md px-3\">\n"
            "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
            "        <h2 class=\"h2 mb-0 py-1\">Česnako skiltelės su klevų sirupu</h2>\n"
            "        <div>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star checked\"></span>\n"
            "          <span class=\"fa fa-star\"></span>\n"
            "          <span class=\"fa fa-star\"></span>\n"
            "          <span class=\"fa fa-star\"></span>\n"
            "        </div>\n"
            "      </div>\n"
            "      <img\n"
            "        src=\"../assets/recipe_3_img.jpg\"\n"
            "        class=\"img-fluid recipe-img mb-3\"\n"
            "        alt=\"\"\n"
            "      />\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p>\n"
            "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
            "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
            "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
            "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
            "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
            "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
            "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
            "        Fusce dictum eleifend odio id pharetra.\n"
            "      </p>\n"
            "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
            "      <ul class=\"list-group\">\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">1 česnako galva</span>\n"
            "        </li>\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">50 ml klevų sirupo</span>\n"
            "        </li>\n"
            "        <li class=\"list-group-item\">\n"
            "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
            "          <span class=\"ingredient\">žiupsnelis druskos</span>\n"
            "        </li>\n"
            "      </ul>\n"
            "    </div>\n"
            "  </body>\n"
            "</html>"
    );

    generate_html_file("receptai/3.html");
    delete_html_code();

    insert_html_text(
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "    <link\n"
        "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link\n"
        "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
        "    <title>Bananais įdaryta vištiena | Reginos Receptai</title>\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
        "    <link\n"
        "      rel=\"stylesheet\"\n"
        "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
        "    />\n"
        "  </head>\n"
        "  <body class=\"pb-4\">\n"
        "    <!-- Navbar -->\n"
        "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
        "      <div class=\"container-md px-3\">\n"
        "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
        "        <button\n"
        "          class=\"navbar-toggler\"\n"
        "          type=\"button\"\n"
        "          data-bs-toggle=\"collapse\"\n"
        "          data-bs-target=\"#navbarSupportedContent\"\n"
        "          aria-controls=\"navbarSupportedContent\"\n"
        "          aria-expanded=\"false\"\n"
        "          aria-label=\"Toggle navigation\"\n"
        "        >\n"
        "          <span class=\"navbar-toggler-icon\"></span>\n"
        "        </button>\n"
        "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
        "          <ul class=\"navbar-nav ms-auto\">\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
        "            </li>\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
        "            </li>\n"
        "          </ul>\n"
        "        </div>\n"
        "      </div>\n"
        "    </nav>\n"
        "\n"
        "    <!-- Page content -->\n"
        "    <div class=\"container-md px-3\">\n"
        "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
        "        <h2 class=\"h2 mb-0 py-1\">Bananais įdaryta vištiena</h2>\n"
        "        <div>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star\"></span>\n"
        "          <span class=\"fa fa-star\"></span>\n"
        "        </div>\n"
        "      </div>\n"
        "      <img\n"
        "        src=\"../assets/recipe_4_img.jpg\"\n"
        "        class=\"img-fluid recipe-img mb-3\"\n"
        "        alt=\"\"\n"
        "      />\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
        "      <ul class=\"list-group\">\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">500 g vištienos file</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">2 bananai</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">1 a. š. druskos</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">2 a. š. aitriųjų pipirų</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">10 a. š. alyvuogių aliejus</span>\n"
        "        </li>\n"
        "      </ul>\n"
        "    </div>\n"
        "  </body>\n"
        "</html>"
    );

    generate_html_file("receptai/4.html");
    delete_html_code();

    insert_html_text(
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "    <link\n"
        "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link\n"
        "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
        "    <title>Lašišos kaulų sriuba iš vietinės aludės | Reginos Receptai</title>\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
        "    <link\n"
        "      rel=\"stylesheet\"\n"
        "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
        "    />\n"
        "  </head>\n"
        "  <body class=\"pb-4\">\n"
        "    <!-- Navbar -->\n"
        "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
        "      <div class=\"container-md px-3\">\n"
        "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
        "        <button\n"
        "          class=\"navbar-toggler\"\n"
        "          type=\"button\"\n"
        "          data-bs-toggle=\"collapse\"\n"
        "          data-bs-target=\"#navbarSupportedContent\"\n"
        "          aria-controls=\"navbarSupportedContent\"\n"
        "          aria-expanded=\"false\"\n"
        "          aria-label=\"Toggle navigation\"\n"
        "        >\n"
        "          <span class=\"navbar-toggler-icon\"></span>\n"
        "        </button>\n"
        "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
        "          <ul class=\"navbar-nav ms-auto\">\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
        "            </li>\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
        "            </li>\n"
        "          </ul>\n"
        "        </div>\n"
        "      </div>\n"
        "    </nav>\n"
        "\n"
        "    <!-- Page content -->\n"
        "    <div class=\"container-md px-3\">\n"
        "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
        "        <h2 class=\"h2 mb-0 py-1\">Lašišos kaulų sriuba iš vietinės aludės</h2>\n"
        "        <div>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star\"></span>\n"
        "          <span class=\"fa fa-star\"></span>\n"
        "        </div>\n"
        "      </div>\n"
        "      <img\n"
        "        src=\"../assets/recipe_5_img.jpg\"\n"
        "        class=\"img-fluid recipe-img mb-3\"\n"
        "        alt=\"\"\n"
        "      />\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
        "      <ul class=\"list-group\">\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">500 ml šaltinio vandens</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">100 ml šalto nealkoholinio alaus</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">2 morkos</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">1 svogūnas</span>\n"
        "        </li>\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">10 a. š. alyvuogių aliejus</span>\n"
        "        </li>\n"
        "      </ul>\n"
        "    </div>\n"
        "  </body>\n"
        "</html>"
    );

    generate_html_file("receptai/5.html");
    delete_html_code();

    insert_html_text(
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "    <link\n"
        "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link\n"
        "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
        "    <title>Pica su kumpiu ir sūriu iš maximos | Reginos Receptai</title>\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
        "    <link\n"
        "      rel=\"stylesheet\"\n"
        "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
        "    />\n"
        "  </head>\n"
        "  <body class=\"pb-4\">\n"
        "    <!-- Navbar -->\n"
        "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
        "      <div class=\"container-md px-3\">\n"
        "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
        "        <button\n"
        "          class=\"navbar-toggler\"\n"
        "          type=\"button\"\n"
        "          data-bs-toggle=\"collapse\"\n"
        "          data-bs-target=\"#navbarSupportedContent\"\n"
        "          aria-controls=\"navbarSupportedContent\"\n"
        "          aria-expanded=\"false\"\n"
        "          aria-label=\"Toggle navigation\"\n"
        "        >\n"
        "          <span class=\"navbar-toggler-icon\"></span>\n"
        "        </button>\n"
        "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
        "          <ul class=\"navbar-nav ms-auto\">\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
        "            </li>\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
        "            </li>\n"
        "          </ul>\n"
        "        </div>\n"
        "      </div>\n"
        "    </nav>\n"
        "\n"
        "    <!-- Page content -->\n"
        "    <div class=\"container-md px-3\">\n"
        "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
        "        <h2 class=\"h2 mb-0 py-1\">Pica su kumpiu ir sūriu iš maximos</h2>\n"
        "        <div>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star\"></span>\n"
        "          <span class=\"fa fa-star\"></span>\n"
        "        </div>\n"
        "      </div>\n"
        "      <img\n"
        "        src=\"../assets/recipe_6_img.jpg\"\n"
        "        class=\"img-fluid recipe-img mb-3\"\n"
        "        alt=\"\"\n"
        "      />\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
        "      <ul class=\"list-group\">\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">1 šaldyta pica</span>\n"
        "        </li>\n"
        "      </ul>\n"
        "    </div>\n"
        "  </body>\n"
        "</html>"
    );

    generate_html_file("receptai/6.html");
    delete_html_code();

    insert_html_text(
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "    <link\n"
        "      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link\n"
        "      href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\"\n"
        "      rel=\"stylesheet\"\n"
        "    />\n"
        "    <link href=\"../styles.css\" rel=\"stylesheet\" />\n"
        "    <title>Proteino bomba | Reginos Receptai</title>\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
        "    <link\n"
        "      rel=\"stylesheet\"\n"
        "      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\n"
        "    />\n"
        "  </head>\n"
        "  <body class=\"pb-4\">\n"
        "    <!-- Navbar -->\n"
        "    <nav class=\"navbar navbar-expand-lg navbar-light mb-3\">\n"
        "      <div class=\"container-md px-3\">\n"
        "        <a class=\"navbar-brand\" href=\"../index.html\">Reginos Receptai</a>\n"
        "        <button\n"
        "          class=\"navbar-toggler\"\n"
        "          type=\"button\"\n"
        "          data-bs-toggle=\"collapse\"\n"
        "          data-bs-target=\"#navbarSupportedContent\"\n"
        "          aria-controls=\"navbarSupportedContent\"\n"
        "          aria-expanded=\"false\"\n"
        "          aria-label=\"Toggle navigation\"\n"
        "        >\n"
        "          <span class=\"navbar-toggler-icon\"></span>\n"
        "        </button>\n"
        "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
        "          <ul class=\"navbar-nav ms-auto\">\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../index.html\">Receptai</a>\n"
        "            </li>\n"
        "            <li class=\"nav-item\">\n"
        "              <a class=\"nav-link\" href=\"../apie.html\">Apie mus</a>\n"
        "            </li>\n"
        "          </ul>\n"
        "        </div>\n"
        "      </div>\n"
        "    </nav>\n"
        "\n"
        "    <!-- Page content -->\n"
        "    <div class=\"container-md px-3\">\n"
        "      <div class=\"page-header d-flex flex-column flex-wrap mb-3\">\n"
        "        <h2 class=\"h2 mb-0 py-1\">Proteino bomba</h2>\n"
        "        <div>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "          <span class=\"fa fa-star checked\"></span>\n"
        "        </div>\n"
        "      </div>\n"
        "      <img\n"
        "        src=\"../assets/recipe_7_img.jpg\"\n"
        "        class=\"img-fluid recipe-img mb-3\"\n"
        "        alt=\"\"\n"
        "      />\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p>\n"
        "        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed turpis\n"
        "        diam, imperdiet quis ex vulputate, vehicula blandit dolor. Mauris\n"
        "        hendrerit neque quis nunc dictum pharetra. Vivamus in velit varius,\n"
        "        sollicitudin elit a, interdum diam. Nunc sed libero faucibus, ultrices\n"
        "        urna ac, aliquam erat. Curabitur sit amet erat sed nunc dapibus viverra.\n"
        "        Vivamus dignissim, est a iaculis blandit, lectus nisi efficitur est, non\n"
        "        molestie libero urna sed nulla. In ut hendrerit ante, eu pretium tortor.\n"
        "        Fusce dictum eleifend odio id pharetra.\n"
        "      </p>\n"
        "      <p class=\"page-section mb-2\">Ingredientai:</p>\n"
        "      <ul class=\"list-group\">\n"
        "        <li class=\"list-group-item\">\n"
        "          <input class=\"form-check-input me-1\" type=\"checkbox\" />\n"
        "          <span class=\"ingredient\">1 žalias kiaušinis</span>\n"
        "        </li>\n"
        "      </ul>\n"
        "    </div>\n"
        "  </body>\n"
        "</html>"
    );

    generate_html_file("receptai/7.html");
    delete_html_code();
    return 0;
}

void insert_recipe_card(const char *title, int rating/*, const char *image_address*/)
{
    static int recipe_number = 0;
    recipe_number++;
    insert_html_tag("div", "class=\"col\"");
    char parameters[75] = "class=\"card rounded-0 border-0 h-100\" href=\"./receptai/";
    char recipe_number_str[10] = {0};
    itoa(recipe_number, recipe_number_str, 10);
    strcat(parameters, recipe_number_str);
    strcat(parameters, ".html\"");
    insert_html_tag("a", parameters);
    char image[80] = "<img\n src=\"./assets/recipe_";
    strcat(image, recipe_number_str);
    strcat(image, "_img.jpg\"\nclass=\"card-img-top rounded-0\"\n/>");
    insert_html_text(image);
    insert_html_tag("div", "class=\"card-body\"");
    insert_html_tag("p", "class=\"card-title h6\"");
    insert_html_text(title);
    exit_html_field(1);
    insert_html_tag("p", "class=\"card-text\"");
    int i;
    for(i = 0; i < rating; i++)
    {
        insert_html_tag("span", "class=\"fa fa-star checked\"");
        exit_html_field(1);
    }
    for(; i < 5; i++)
    {
        insert_html_tag("span", "class=\"fa fa-star\"");
        exit_html_field(1);
    }
    exit_html_field(4);
}

void insert_html_tag_and_exit(char *tag, char *attributes)
{
    insert_html_tag(tag, attributes);
    exit_html_field(1);
}

void insert_html_tag_with_text(char *tag, char *attributes, char *text)
{
    insert_html_tag(tag, attributes);
    insert_html_text(text);
    exit_html_field(1);
}

void add_css()
{
    insert_html_text(
            "@import url(\"https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;1,400;1,700&family=Open+Sans&display=swap\");"
            ":root {"
                "--primary-font: \"Merriweather\", serif;"
                "--secondary-font: \"Open Sans\", sans-serif;"
                "--primary-font-color: #514343;"
                "--primary-font-color-hover: #a19a98;"
                "--secondary-font-color: #3b2222;"
                "--primary-background-color: #ede9e4;"
                "--light-background-color: #f8f5f1;"
                "--light-border: 1px solid #ebe1d6;"
                "--font-weight-bold: 700;"
            "}"
            "body {"
                "font-family: var(--secondary-font);"
                "color: var(--secondary-font-color);"
            "}"
            ".navbar {"
                "background-color: var(--primary-background-color);"
                "color: var(--primary-font-color);"
            "}"
            ".navbar-brand {"
                "font-family: var(--primary-font);"
                "color: inherit;"
                "transition: color 200ms ease-in-out;"
            "}"
            ".nav-link {"
                "text-transform: uppercase;"
                "color: inherit;"
            "}"
            ".nav-link:hover, .navbar-brand:hover {"
                "color: var(--primary-font-color-hover);"
            "}"
            ".page-header {"
                "font-family: var(--primary-font);"
                "color: var(--primary-font-color);"
            "}"
            ".fa-star {"
                "color: #514343;"
            "}"
            ".checked {"
                "color: #dfbb62;"
            "}"
            ".card {"
                "text-decoration: none;"
                "color: inherit;"
                "transition: opacity 200ms ease-in-out;"
            "}"
            ".card:hover {"
                "opacity: 0.8;"
            "}"
            ".card-body {"
                "background-color: var(--light-background-color);"
                "border-bottom: var(--light-border);"
            "}"
            ".card-title {"
                "color: var(--primary-font-color);"
                "font-family: var(--primary-font);"
            "}"
            ".page-section {"
                "font-family: var(--primary-font);"
                "font-weight: var(--font-weight-bold);"
                "color: var(--primary-font-color);"
            "}"
            ".ingredient {"
                "color: var(--secondary-font-color);"
            "}"
            ".container-md {"
                "max-width: 1220px;"
            "}"
            ".card-img-top {"
                "width: 100%;"
                "height: 15vw;"
                "min-height: 180px;"
                "max-height: 300px;"
                "object-fit: cover;"
            "}"
            ".recipe-img {"
                "max-height: 25vw;"
                "min-height: 240px;"
                "width: 100%;"
                "object-fit: cover;"
            "}"
            ".sort-select {"
                "min-width: 240px;"
                "color: var(--primary-font-color);"
                "font-family: var(--secondary-font);"
            "}"
            "option {"
                "font-family: inherit;"
                "color: inherit;"
            "}"
    );
}

void insert_boilerplate()
{
    insert_html_text("<!DOCTYPE html>");
    insert_html_tag("html", "lang=\"en\"");
    insert_html_tag("head", NULL);
    insert_html_tag_and_exit("meta", "charset=\"utf-8\"");
    insert_html_tag_and_exit("meta", "name=\"viewport\" content=\"width=device-width, initial-scale=1\"");
    insert_html_tag_and_exit("link", "href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"");
    insert_html_tag_and_exit("link", "href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\" rel=\"stylesheet\"");
    insert_html_tag_and_exit("link", "href=\"styles.css\" rel=\"stylesheet\"");
    insert_html_tag_with_text("title", NULL, "Reginos Receptai");
    insert_html_tag_and_exit("script", "src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"");
    insert_html_tag_and_exit("link", "rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"");
    exit_html_field(1);
    insert_html_tag("body", "class=\"pb-4\"");
}

void insert_navbar()
{
    insert_html_tag("nav", "class=\"navbar navbar-expand-lg navbar-light mb-3\"");
    insert_html_tag("div", "class=\"container-md px-3\"");
    insert_html_tag_with_text("a", "class=\"navbar-brand\" href=\"./index.html\"", "Reginos Receptai");
    insert_html_tag("button", "class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"");
    insert_html_tag("span", "class=\"navbar-toggler-icon\"");
    exit_html_field(2);
    insert_html_tag("div", "class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\"");
    insert_html_tag("ul", "class=\"navbar-nav ms-auto\"");
    insert_html_tag("li", "class=\"nav-item\"");
    insert_html_tag_with_text("a", "class=\"nav-link\" href=\"./index.html\"", "Receptai");
    exit_html_field(1);
    insert_html_tag("li", "class=\"nav-item\"");
    insert_html_tag_with_text("a", "class=\"nav-link\" href=\"./apie.html\"", "Apie mus");
    exit_html_field(5);
}

void insert_main_page()
{
    insert_boilerplate();
    insert_navbar();
    insert_html_tag("div", "class=\"container-md px-3\"");
    insert_html_tag("div", "class=\"page-header d-flex flex-wrap mb-2 justify-content-between align-items-center\"");
    insert_html_tag_with_text("h2", "class=\"h5 mb-0 py-2\"", "Ką gaminam?");
    insert_html_tag("select", "class=\"form-select w-25 sort-select\" aria-label=\"Rūšiuoti receptus\"");
    insert_html_tag_with_text("option", "value=\"0\" selected", "Geriausiai įvertinti");
    insert_html_tag_with_text("option", "value=\"1\"", "Prasčiausiai įvertinti");
    insert_html_tag_with_text("option", "value=\"2\"", "Naujausi");
    insert_html_tag_with_text("option", "value=\"3\"", "Seniausi");
    exit_html_field(2);
    insert_html_tag("div", "class=\"row row-cols-1 row-cols-md-3 g-4\"");
    insert_recipe_card("Ryžiadešriai", 4);
    insert_recipe_card("Pieniška agurkų sriuba", 3);
    insert_recipe_card("Česnako skiltelės su klevų sirupu", 2);
    insert_recipe_card("Bananais įdaryta vištiena", 3);
    insert_recipe_card("Lašišos kaulų sriuba iš vietinės aludės", 3);
    insert_recipe_card("Pica su kumpiu ir sūriu iš maximos", 3);
    insert_recipe_card("Proteino bomba", 5);
}